# Generated by Django 3.1.3 on 2020-12-03 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordgame', '0001_initial_force_migrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('daily_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordgame.christmasword')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
