# Generated by Django 3.2.9 on 2021-12-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0004_auto_20211126_1105'),
        ('wordgame', '0004_auto_20211213_2151'),
    ]

    operations = [
    ]
