# Generated by Django 3.2.9 on 2021-12-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_auto_20211126_1105'),
        ('gift', '0002_auto_20211213_2151'),
    ]

    operations = [
    ]
