# Generated by Django 3.2.9 on 2021-12-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsit', '0004_auto_20211126_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='correct_description',
            field=models.TextField(),
        ),
    ]
